Feat/signature
3cn-ecn/nantralPlatform pull request #1146
Opened 2023-10-28 20:58 UTC by hydrielax

# Description

A new module for signature in React!

- Autofill name, year, option, clubs and email
- Export to HTML, plain text or HTML source code
- Auto-copy to clipboard

2023-10-30 20:36 UTC, rravelli reviewed
Top ! Génial de pouvoir choisir comment copier la signature. On merge ça après ma PR :eyes:

2023-10-30 20:49 UTC, rravelli requested changes
Je viens de m'apercevoir d'un problème, lorsque tu changes d'onglet axios réeffectue ses requêtes et reset la signature. C'est vachement embêtant !

2023-11-01 20:09 UTC, hydrielax commented
> Je viens de m'apercevoir d'un problème, lorsque tu changes d'onglet axios réeffectue ses requêtes et reset la signature. C'est vachement embêtant !

C'est fix normalement ! J'ai réglé le staleTime sur Infinity (c'est ce qui est recommandé par la doc de react query quand tu n'utilises pas directement le state)

2023-11-04 12:55 UTC, rravelli approved these changes

2023-11-05 14:56 UTC, merged