React app bug
3cn-ecn/nantralPlatform pull request #981
Opened 2023-03-14 17:56 UTC by Corentin09

Implémentations d'un formulaire de suggestion/ Bug, permettant à un utilisateur de Nantral Platform de signaler un bug ou de proposer une suggestion. Le form génère alors automatiquement une issue sur Github, avec les informations de l'utilisateur. 
<img width="1413" alt="Capture d’écran 2023-03-14 à 18 52 47" src="https://user-images.githubusercontent.com/112824302/225094536-73b412ca-dcce-4167-9b9f-0ee7cbd1a632.png">

<img width="732" alt="Capture d’écran 2023-03-14 à 18 53 14" src="https://user-images.githubusercontent.com/112824302/225094648-6279af14-949c-4077-8d39-a49d5f7fe8a6.png">

<img width="1274" alt="Capture d’écran 2023-03-14 à 18 53 39" src="https://user-images.githubusercontent.com/112824302/225094741-640ceb79-8501-42ca-958c-5838957887db.png">

<img width="967" alt="Capture d’écran 2023-03-14 à 18 53 59" src="https://user-images.githubusercontent.com/112824302/225094807-1d066006-7722-4d1d-b51e-16f220c3af8b.png">

Implémentation d'une page de profil pour chaque utilisateurs. De plus, les utilisateurs, peuvent accéder à leurs propres pages de profil, en cliquant sur le bouton mon Profil

<img width="1440" alt="Capture d’écran 2023-03-14 à 18 54 24" src="https://user-images.githubusercontent.com/112824302/225094890-bf7d2547-c8fd-4b7b-9899-d2fa4bf46139.png">

Implémentations de nombreux ajouts mineurs, comme un avatar affichant les photos de profil, des changements sur les contenus et l'organisation des menus, la possibilité de marquer des notifications comme lues, sans les ouvrir

<img width="1432" alt="Capture d’écran 2023-03-14 à 18 55 57" src="https://user-images.githubusercontent.com/112824302/225095262-8395c1d5-46b9-4076-ae3d-a107edc31873.png">

2023-03-14 19:43 UTC, hydrielax requested changes
@Corentin09 Voili voilou, beaucoup de blabla mais bon en soi par rapport à tout ce qui est fait c'est pas grand chose ^^
Des bisous

2023-03-14 19:43 UTC, hydrielax commented on backend/apps/home/api_views.py
> +        return redirect('/')
Tu n'as pas besoin de renvoyer une url, tu peux juste renvoyer une réponse avec le statut 200 pour dire que tout s'est bien passé :
```python
from rest_framework import response, status

return response.Response(status=status.HTTP_200_OK)
```

2023-03-14 19:43 UTC, hydrielax commented on backend/apps/utils/github.py
> +    print(body)
remove print

2023-03-14 19:43 UTC, hydrielax commented on backend/apps/utils/github.py
> +    label = "bug" if label == "Bug" else "suggestion"
si tu dois modifier la valeur de `label`, fait le plutôt dans la view plutôt qu'ici : ça te permet de renvoyer une réponse avec une erreur depuis la view si le label n'est pas correct

Aussi ajoute le type du label dans la signature de la fonction python : 
```python
def create_issue(title: str, body: str, label: Literal['bug', 'suggestion']) -> None:
```

Tu peux aussi ajouter un `try... except` dans la view pour gérer les cas ou `create_issue` renvoie une erreur, et gérer cette erreur pour qu'elle soit renvoyée par l'api et que tu puisses l'afficher dans le frontend (dans une view, pour renvoyer une erreur il faut utiliser : `raise exceptions.[...]` avec `exceptions` importé depuis `rest_framework` (si ce n'est pas une classe d'exception importée de rest_framework ça renverra une erreur 500 sans explications ni message d'erreurs au frontend)

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/App.tsx
> +            <Route path="/student/:studentId/" element={<Profile />} />
Attention à rester cohérent : il y a un slash à la fin de cette url mais pas à la fin des autres urls du router de react, il faudrait normaliser

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/FormProfil/FormProfil.tsx
> + */
JSDoc oubliée cherche fonction à laquelle se rattacher

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/FormProfil/FormProfil.tsx
> +  type: string;
idem pour le type, précise plus exactement le type : `type: 'bug' | 'suggestion'`

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/FormProfil/FormProfil.tsx
> +  const defaultFields: FieldType[] = [
Plutôt que d'indiquer le type sur la variable, indique le type sur la signature de la fonction pour spécifier ce qu'elle renvoie : 
```ts
function createFormFields(): FieldType[] {
```
TypeScript comprendra ensuite tout seul que la variable est de ce type par inférence

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/FormProfil/FormProfil.tsx
> +export function EditProfilModal(props: {
Attention ton composant c'est pour le form de suggestion ou le form d'édition du profil utilisateur ? Faut éviter de tout mélanger, si besoin crée plutôt un composant générique "ModalForm" qui permet d'afficher un form dans un modal et que tu peux réutiliser pour les deux si tu veux

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/MembershipsGroup.tsx
> +import React, { useState, useEffect } from 'react';
Pourquoi l'avoir copié ici ? Faut pas tout copier bêtement du legacy, le but est de ne recopier que les éléments qui vous servent et des les ranger proprement dans la nouvelle structure React au fur-et-à-mesure que vous les ajoutez

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/MembershipsStudent.tsx
> +import React, { useState, useEffect } from 'react';
idem

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/components/Avatar.tsx
> +import React from 'react';
idem, pourrait être exporté en composant racine directement s'il peut être réutilisé à plusieurs endroits

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/components/CardMembership.tsx
> +import React, { useState } from 'react';
idem

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/components/ListMembershipsGrid.tsx
> +import React from 'react';
bis repætita

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/components/ListMembershipsTable.tsx
> +import React, { useState } from 'react';
bis repætita placent

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/components/ModalDeleteMember.tsx
> +import React, { useState } from 'react';
bis repætita ne placent pas toujours

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/components/ModalDisplayMember.tsx
> +import React from 'react';
rebelote

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/components/ModalEditMember.tsx
> +import React, { FormEvent, useState } from 'react';
rerebelote

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Group/interfaces.ts
> +export interface SimpleGroup {
bis

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/NavBarTop/NavBarTop.tsx
> +  Avatar,
Utilises plutôt le composant `Avatar` custom que j'ai codé dans `Group` pour afficher les initiales de l'utilisateur quand il n'a pas de photo (ça permet d'être cohérent sur l'ensemble de l'interface)

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/NavBarTop/NavBarTop.tsx
> +  };
Est-ce vraiment nécessaire d'écrire une fonction juste pour ça, vous pouvez pas directement appeler `() => setOpenS(true)` dans le code JSX ?

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/NotificationMenu/NotificationItem.tsx
> +            <Avatar
Même remarque pour l'avatar que le précédent, utilises plutôt le composant custom qui permet d'afficher les initiales si pas d'image

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Suggestion/Suggestion.tsx
> +        item: ['Bug', 'Suggestion'],
Dans un select, les items doivent être une liste de couples (valeur, label) normalement (les valeurs étant ce qui sera envoyé au backend, et les labels ce qui est affiché à l'utilisateur et qui peut être traduit) 
cf l'exemple en HTML pur : https://developer.mozilla.org/fr/docs/Web/HTML/Element/select

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/components/Suggestion/Suggestion.tsx
> +                // eslint-disable-next-line react/jsx-no-useless-fragment
Mets directement le composant `CircularProgress`, avec un attribut `hidden={!saving}` pour éviter d'utiliser un opérateur ternaire

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/legacy/group/MembershipsGroup.tsx
> +import { Snackbar, Alert, Button, Box, IconButton } from '@mui/material';
Annuler toutes les modifs faites au legacy (sauf si elles sont vraiment valables), git permet de le faire en deux-trois clics normalement en cherchant un peu

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/pages/Profile/Profile.tsx
> +  function getFaculty(fac) {
Plus simple de faire drectement un object ici qui sert de référence : 
```js
const faculty = {
   'Gen': t('...'),
   ...
}
```

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/utils/axios.ts
> +/**
**A SUPPRIMER**

Explications (parce que oui je vous ais jamais parlé de ça) : axios a besoin d'être configuré avant d'être utilisé, il fallait le faire manuellement pour chaque fichier dans le legacy (d'où l'existance de ce utils), mais pour react il est configuré directement dans `App.js` donc pas besoin de ce utils, il faut directement importer `import axios from 'axios'` au lieu `import axios from '../../utils/axios'`

2023-03-14 19:43 UTC, hydrielax commented on frontend/src/utils/formatUrl.ts
> +// DO NOT USE ANYMORE !!! REPLACE BY FETCH API
Le commentaire était clair pourtant non ? A ceci près qu'il faut le remplacer par axios directement

2023-03-14 22:44 UTC, Corentin09 commented on frontend/src/components/Group/MembershipsStudent.tsx
> +import React, { useState, useEffect } from 'react';
Celui-ci me sert, techniquement, vu qu'il me permet d'afficher les clubs dans la page de profile (après, je ne dit pas pour les autres)

2023-03-14 22:50 UTC, Corentin09 commented on frontend/src/components/Group/components/CardMembership.tsx
> +import React, { useState } from 'react';
Et du coup, pour ce composant et les suivants, je dois les utiliser pour Membership/Student, donc je pensais que le mieux serait de les avoir dans un dossier associé

2023-03-14 22:51 UTC, Corentin09 commented on frontend/src/components/NavBarTop/NavBarTop.tsx
> +  };
Si, mais c'est moins rigolo si c'est trop simple

2023-03-14 22:54 UTC, Corentin09 commented on frontend/src/utils/formatUrl.ts
> +// DO NOT USE ANYMORE !!! REPLACE BY FETCH API
Oupsi 🙃

2023-03-14 22:55 UTC, Corentin09 commented on backend/apps/home/api_views.py
> +    """A view to query the external Geocoding service."""
Oupsi 🙃

2023-03-14 22:55 UTC, Corentin09 commented on backend/apps/utils/github.py
> +    print(body)
Oupsi 🙃 x2

2023-03-14 22:56 UTC, Corentin09 commented on backend/apps/utils/github.py
> +    label = "bug" if label == "Bug" else "suggestion"
Le type, c'est fait, je verrai pour l'exception un peu plus tard je pense, je vais déjà essayer de corriger le reste

2023-03-14 22:56 UTC, Corentin09 commented on frontend/src/App.tsx
> +            <Route path="/student/:studentId/" element={<Profile />} />
Oupsi 🙃 x3

2023-03-14 22:59 UTC, Corentin09 commented on frontend/src/components/FormProfil/FormProfil.tsx
> +export function EditProfilModal(props: {
C'est surtout que le form de modification utilisateur est pas encore totalement fini, donc je le laisse de coté pour l'instant, et j'ai donc pas pris le temps de le rendre au propre, pour l'instant. Mais je vais essayer de rendre ça plus clair

2023-03-14 22:59 UTC, Corentin09 commented on frontend/src/components/Group/MembershipsGroup.tsx
> +import React, { useState, useEffect } from 'react';
Effectivement, celui-là n'a rien n'a faire là, je l'enlève sur le champ

2023-03-14 23:00 UTC, Corentin09 commented on frontend/src/components/Group/components/ModalDeleteMember.tsx
> +import React, { useState } from 'react';
De même x3

2023-03-14 23:00 UTC, Corentin09 commented on frontend/src/components/Group/components/ModalDisplayMember.tsx
> +import React from 'react';
De même x4

2023-03-14 23:00 UTC, Corentin09 commented on frontend/src/components/Group/components/ModalEditMember.tsx
> +import React, { FormEvent, useState } from 'react';
De même x5

2023-03-14 23:02 UTC, Corentin09 commented on frontend/src/components/NavBarTop/NavBarTop.tsx
> +  Avatar,
L'idée était que l'icône de base remplace l'Avatar dans ces cas-là, mais je peux aussi modifier ça pour utiliser ton composant

2023-03-14 23:02 UTC, Corentin09 commented on frontend/src/components/NotificationMenu/NotificationItem.tsx
> +            <Avatar
De même, j'avais gardé le comportement de l'ancien site qui affichait le logo du site, mais c'est effectivement plus pertinent d'utiliser ton composant dans ce cas là

2023-03-15 12:09 UTC, hydrielax commented on frontend/src/components/Group/components/CardMembership.tsx
> +import React, { useState } from 'react';
Je suis d'accord du coup, sauf pour Avatar qui peut être réutilisé ailleurs aussi donc mériterait à être exporté plus globalement

2023-03-17 08:18 UTC, Corentin09 commented on frontend/src/components/Group/components/CardMembership.tsx
> +import React, { useState } from 'react';
C'est bien ce que j'ai fait, du coup

2023-03-17 09:02 UTC, Corentin09 commented on frontend/src/components/Suggestion/Suggestion.tsx
> +                // eslint-disable-next-line react/jsx-no-useless-fragment
J'ai pas l'impression qu'il y ait un attribut `hidden` pour `CircularProgress,` en tout cas, celui-ci n'est pas caché  lorsque que je l'ajoute et je l'ai pas vu dans les attributs associé dans la doc de Mui

2023-03-17 11:06 UTC, merged